server:
  port: 9100
spring:
  application:
    name: reggie_take_out
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.136.131:3306/reggie?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: 123456
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.136.132:3306/reggie?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: 123456
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
    mvc:
      hiddenmethod:
        filter:
          enabled: true
  redis:
    host: 127.0.0.1
    post: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
reggie_take_out:
  path:  D:\DevelopmentTool\ideaProjects\JavaSE_Code\picture\image

